[package]
name = "ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
lambda_http = { workspace = true }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }